---
- name: Smart Playbook
  hosts: test

  tasks:
  - name: Update apt cache and install Python3
    apt: 
        name: python3
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Stop firewall
    service: 
        name: ufw
        state: stopped
        enabled: no
    when: ansible_distribution == "Ubuntu"


  - name: Update apt cache and install Python3
    yum:
        name: python3
        update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Stop firewall
    service:
        name: firewalld
        state: stopped
        enabled: no
    when: ansible_distribution == "CentOS"


- name: file module and lineinfile module
  hosts: all

  tasks: 

  - name: Include variables from 'config.yaml'
    include_vars:
            file: config.yaml

  - name: create a file called 'UpdatedHelloworld' in the '/' directory
    file:
            path: '/UpdatedHelloworld'
            state: touch
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: '0755'

  - name: Insert a line inside the 'UpdatedHelloworld' file
    lineinfile:
            path: '/UpdatedHelloworld'
            line: 'This file is created and updated using the file and lineinfile modules'
            state: present

  - name: Copy 'myname' to the /home/vagrant directory 
    copy:
            src: myname
            dest: "/home/{{ user }}/myname"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: '0755'

  - name: View content of 'myname'
    shell: "cat /home/{{ user }}/myname"
    register: output

  - name: Show ouput of 'myname'
    debug:
            var: output  
